feat: [Identity] add env configuration of the connection to keycloak
camunda/camunda-platform-helm pull request #337
Opened 2022-06-27 15:09 UTC by piermotte

### Related issues

### What's in this PR?

Allow to set `KEYCLOAK_URL`and `IDENTITY_AUTH_PROVIDER_BACKEND_URL` in case keycloak must be accessible through https.

### Which problem does the PR fix?

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added.
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### To-Do

- [ ] If the PR is not complete but you want to discuss the approach,
  list what remains to be done here.

2022-06-27 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-platform-helm?pullRequest=337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-platform-helm?pullRequest=337) before we can accept your contribution.<br/><hr/>**Pierre MOTTE** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-platform-helm?pullRequest=337) it.</sub>

2022-06-28 06:40 UTC, Zelldon requested changes
Thanks for your contribution @piermotte 

the changes are not really clear to me. Why was this necessary? Please elaborate a bit on this. 
You need to sign the CLA before we continue here.

2022-06-28 10:48 UTC, piermotte commented
hi @Zelldon, my bad, i forgot to add comment.
I need this change to call my keycloak instance through ingress which use `https`

2022-08-18 10:15 UTC, aabouzaid commented
@piermotte Thanks for your contribution :clap: 

However, without signing the CLA (check 2nd comment in this PR), and without adding details about the use case or the proposed change we cannot proceed with this PR.

2022-08-31 11:09 UTC, aabouzaid requested changes
I've changed the PR to draft and if there is any update about it then it could be changed when it's ready.

2022-09-28 23:17 UTC, buildwithjz commented
Thanks @piermotte for raising this. I think this PR opens up the possibility for users to bring their own instance of keycloak - as `KEYCLOAK_URL` and `IDENTITY_AUTH_PROVIDER_BACKEND_URL` are essentially free-text fields. 

That being said, I request for conditional dependency support for the `keycloak` chart be set as part of the `identity` chart to allow users to specify whether Helm creates a brand new instance of keycloak or not

https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/identity/Chart.yaml#L11

2022-09-29 10:06 UTC, piermotte commented
Hi @buildwithjz, thanks for your review, is this what you had in mind ?
`condition: "keycloak.enabled"`

2022-10-14 08:26 UTC, mhuijgen commented
Using an external keycloak instance with the camunda helm chart would be very helpful to us.

2022-10-24 18:33 UTC, aabouzaid commented
The changes in this PR missing crucial parts of enabling existing/external Keycloak.
And since this feature was planned to the next release, I've created a new PR (#451) to introduce this feature.

So this will be in the next Camunda Platform Helm chart release.

2022-10-24 18:33 UTC, closed without merging