Use keycloakURL instead of keycloakURLBase
camunda/camunda-platform-helm pull request #758
Opened 2023-07-03 04:38 UTC by joshuatam

to follow global.identity.keycloak.url in self-managed setup

### Which problem does the PR fix?

### What's in this PR?

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

2023-07-03 04:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-platform-helm?pullRequest=758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-platform-helm?pullRequest=758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-platform-helm?pullRequest=758) it.</sub>

2023-07-12 10:48 UTC, aabouzaid commented
@joshuatam thanks for the PR :bow: 
Please run `make go.test-golden-updated` and push the changes.

2023-07-13 10:19 UTC, aabouzaid requested changes
Once the golden files are updated, I will process with this PR.

2023-07-30 07:28 UTC, joshuatam commented
Failed when running `make go.test-golden-updated`

```
--- FAIL: TestDeploymentTemplate (273.61s)
    --- FAIL: TestDeploymentTemplate/TestContainerSetInboundModeOauth (5.49s)
        deployment_test.go:773: 
                Error Trace:    /home/joshua/Projects/camunda-platform-helm/charts/camunda-platform/test/unit/connectors/deployment_test.go:773
                Error:          []v1.EnvVar{v1.EnvVar{Name:"SERVER_PORT", Value:"8080", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL", Value:"http://camunda-platform-test-keycloak:80/auth", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_CLIENT-ID", Value:"connectors", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_CLIENT-SECRET", Value:"", ValueFrom:(*v1.EnvVarSource)(0xc00007fea0)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM", Value:"camunda-platform", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"OPERATE_CLIENT_ENABLED", Value:"true", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_URL", Value:"http://camunda-platform-test-operate:80", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS", Value:"camunda-platform-test-zeebe-gateway:26500", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_SECURITY_PLAINTEXT", Value:"true", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_ID", Value:"zeebe", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_SECRET", Value:"", ValueFrom:(*v1.EnvVarSource)(0xc00007fec0)}, v1.EnvVar{Name:"ZEEBE_AUTHORIZATION_SERVER_URL", Value:"http://camunda-platform-test-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_TOKEN_AUDIENCE", Value:"zeebe-api", ValueFrom:(*v1.EnvVarSource)(nil)}} does not contain v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL", Value:"http://camunda-platform-test-keycloak:80", ValueFrom:(*v1.EnvVarSource)(nil)}
                Test:           TestDeploymentTemplate/TestContainerSetInboundModeOauth
FAIL
FAIL    camunda-platform-helm/charts/camunda-platform/test/unit/connectors      273.857s
```

2023-07-31 13:23 UTC, aabouzaid commented
> Failed when running `make go.test-golden-updated`
> 
> ```
> --- FAIL: TestDeploymentTemplate (273.61s)
>     --- FAIL: TestDeploymentTemplate/TestContainerSetInboundModeOauth (5.49s)
>         deployment_test.go:773: 
>                 Error Trace:    /home/joshua/Projects/camunda-platform-helm/charts/camunda-platform/test/unit/connectors/deployment_test.go:773
>                 Error:          []v1.EnvVar{v1.EnvVar{Name:"SERVER_PORT", Value:"8080", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL", Value:"http://camunda-platform-test-keycloak:80/auth", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_CLIENT-ID", Value:"connectors", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_CLIENT-SECRET", Value:"", ValueFrom:(*v1.EnvVarSource)(0xc00007fea0)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM", Value:"camunda-platform", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"OPERATE_CLIENT_ENABLED", Value:"true", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_URL", Value:"http://camunda-platform-test-operate:80", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS", Value:"camunda-platform-test-zeebe-gateway:26500", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_SECURITY_PLAINTEXT", Value:"true", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_ID", Value:"zeebe", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_CLIENT_SECRET", Value:"", ValueFrom:(*v1.EnvVarSource)(0xc00007fec0)}, v1.EnvVar{Name:"ZEEBE_AUTHORIZATION_SERVER_URL", Value:"http://camunda-platform-test-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token", ValueFrom:(*v1.EnvVarSource)(nil)}, v1.EnvVar{Name:"ZEEBE_TOKEN_AUDIENCE", Value:"zeebe-api", ValueFrom:(*v1.EnvVarSource)(nil)}} does not contain v1.EnvVar{Name:"CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL", Value:"http://camunda-platform-test-keycloak:80", ValueFrom:(*v1.EnvVarSource)(nil)}
>                 Test:           TestDeploymentTemplate/TestContainerSetInboundModeOauth
> FAIL
> FAIL    camunda-platform-helm/charts/camunda-platform/test/unit/connectors      273.857s
> ```
> 
> Maybe there is another location need to change?

You need to update the test to match the change.

So you need to change the assertion of the var `CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL` in [TestContainerSetInboundModeOauth](https://github.com/camunda/camunda-platform-helm/blob/c11b321475580e88b31d2d8da19c2d0f30f2c7c2/charts/camunda-platform/test/unit/connectors/deployment_test.go#L744).

2023-07-31 13:24 UTC, aabouzaid commented
@igpetrov could you please verify if that change is expected?

2023-08-19 17:20 UTC, closed without merging