Remove minimumMasterNodes from camunda-platform-core-kind-values.yaml
camunda/camunda-platform-helm pull request #794
Opened 2023-07-18 08:56 UTC by falko

### Which problem does the PR fix?
minimumMasterNodes is ignored in Elasticsearch versions >= 7 according to https://github.com/elastic/helm-charts/blob/main/elasticsearch/README.md#configuration

### What's in this PR?
Remove minimumMasterNodes from camunda-platform-core-kind-values.yaml

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

2023-07-21 15:21 UTC, jessesimpson36 commented
I tested by setting:
```
elasticsearch:
  minimumMasterNodes: 100
```
and confirmed that nothing happened. I also read the elasticsearch helm chart and verified that this option is not actually used.  I approve.

2023-07-21 15:23 UTC, jessesimpson36 approved these changes

2023-07-21 15:24 UTC, jessesimpson36 commented
I'll merge in a moment. I'll probably rename the merge commit so that it fits our commit naming guidelines

2023-07-21 15:27 UTC, jessesimpson36 commented
Hmm.. I wonder why our CI didn't automatically trigger for this change.

2023-07-21 15:48 UTC, jessesimpson36 requested changes
Please change the commit message to follow our [commit guidelines](https://github.com/camunda/camunda-platform-helm/blob/main/CONTRIBUTING.md#commit-guidelines).  

You can do that by 
```
git rebase -i main
```
And then it will open an editor where you can edit the commit.

I believe this will also cause CI to trigger. I suspect your last push happened during some partial github outage and that's why CI didn't run.

2023-08-04 09:07 UTC, aabouzaid commented
> Hmm.. I wonder why our CI didn't automatically trigger for this change.

we don't have a CI pipeline for KIND yet.

2023-08-04 09:08 UTC, aabouzaid approved these changes

2023-08-04 09:09 UTC, merged