fix: added reasonable default proxy-buffer-size
camunda/camunda-platform-helm pull request #902
Opened 2023-09-22 13:47 UTC by jessesimpson36

### Which problem does the PR fix?

### What's in this PR?

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

2023-09-25 17:33 UTC, aabouzaid commented
@jessesimpson36, you probably just need to run `make go.test-golden-updated` in the repo's root to update the golden file.

2023-09-25 17:39 UTC, aabouzaid requested changes
@jessesimpson36, you probably just need to run `make go.test-golden-updated` in the repo's root to update the golden file.

2023-09-26 17:53 UTC, aabouzaid commented
I've quickly updated the golden files to merge the PR.

2023-09-26 17:54 UTC, merged

2023-10-02 15:55 UTC, jessesimpson36 commented
Thanks, sorry I fell off of this topic!